Exit on unsupported event

diff --git a/terragrunt/find-changes/action.yml b/terragrunt/find-changes/action.yml
--- a/terragrunt/find-changes/action.yml
+++ b/terragrunt/find-changes/action.yml
@@ -36,7 +36,8 @@ runs:
             ;;
 
           *)
-            changed_files=""
+            echo "Error: Unsupported event received: ${GITHUB_EVENT_NAME}. Only pull_request and push are supported. Exiting."
+            exit 1
             ;;
 
         esac
