Use inputs

diff --git a/terragrunt/find-changes/action.yml b/terragrunt/find-changes/action.yml
--- a/terragrunt/find-changes/action.yml
+++ b/terragrunt/find-changes/action.yml
@@ -5,6 +5,12 @@ inputs:
   github-token:
     description: GitHub auth token
     required: true
+  pr-number:
+    description: Pull request number. Either head-commit or pr-number must be given.
+    required: false
+  head-commit:
+    description: Head commit sha. Either head-commit or pr-number must be given.
+    required: false
 
 outputs:
   updates:
@@ -26,21 +32,14 @@ runs:
           fi
         }
 
-        case "${GITHUB_EVENT_NAME}" in
-          pull_request)
-            changed_files="$(gh api repos/{owner}/{repo}/pulls/${PR_NUMBER}/files --paginate)"
-            ;;
-
-          push)
-            changed_files="$(gh api repos/{owner}/{repo}/commits/${HEAD_COMMIT} --paginate --jq .files)"
-            ;;
-
-          *)
-            echo "Error: Unsupported event received: ${GITHUB_EVENT_NAME}. Only pull_request and push are supported. Exiting."
-            exit 1
-            ;;
-
-        esac
+        if [ -n "${PR_NUMBER}" ]; then
+          changed_files="$(gh api repos/{owner}/{repo}/pulls/${PR_NUMBER}/files --paginate)"
+        elif [ -n "${HEAD_COMMIT}" ]; then
+          changed_files="$(gh api repos/{owner}/{repo}/commits/${HEAD_COMMIT} --paginate --jq .files)"
+        else
+          echo "Error: Either head-commit or pr-number must be be given. Exiting."
+          exit 1
+        fi
 
         updates=$(for f in $(echo "${changed_files}" | jq -r '.[] | select(.status != "removed") | .filename'); do
           print_path "$f"
@@ -56,5 +55,5 @@ runs:
       shell: bash
       env:
         GITHUB_TOKEN: ${{ inputs.github-token }}
-        PR_NUMBER: ${{ github.event.pull_request.number }}
-        HEAD_COMMIT: ${{ github.event.head_commit.id }}
+        PR_NUMBER: ${{ inputs.pr-number }}
+        HEAD_COMMIT: ${{ inputs.head_commit }}
